import type {
  AdminDispute,
  AdminNotification,
  AdminPayment,
  AdminPayout,
  AdminProperty,
  AdminUser,
  AdminVerification,
  AuditLog,
  EscrowSummary,
  OverviewStats,
  SupportTicket,
} from "~/services/api/types";

export const MOCK_STATS: OverviewStats = {
  welcomeName: "Emmanuel",
  activeListings: 1284,
  listingChangePct: 12,
  escrowVolumeNgn: 48_400_000,
  escrowChangePct: 8,
  pendingVerification: 47,
  pendingPriorityLabel: "High Priority",
  trend: [
    { month: "Jan", volume: 80_000_000, released: 55_000_000 },
    { month: "Feb", volume: 95_000_000, released: 70_000_000 },
    { month: "Mar", volume: 110_000_000, released: 150_000_000 },
    { month: "Apr", volume: 120_000_000, released: 240_000_000 },
    { month: "May", volume: 140_000_000, released: 180_000_000 },
    { month: "Jun", volume: 160_000_000, released: 210_000_000 },
    { month: "July", volume: 175_000_000, released: 230_000_000 },
  ],
  listingsByState: [
    { state: "Lagos", count: 400 },
    { state: "Abuja", count: 300 },
    { state: "Delta", count: 310 },
    { state: "Enugu", count: 300 },
  ],
  attention: [
    {
      id: "att-1",
      title: "Oluwaseun Adeyemi",
      detail: "CAC Documents Uploaded. Submitted 2 days ago.",
      kind: "kyc",
      status: "pending",
      priority: "high",
      href: "/users/user-emeka",
    },
    {
      id: "att-2",
      title: "Property #LP-4821 flagged for review",
      detail: "Price discrepancy detected - listed at N85M vs Avg. Market.",
      kind: "listing",
      status: "pending",
      priority: "high",
      href: "/properties/prop-1",
    },
    {
      id: "att-3",
      title: "REQ-2026-338 - Overdue by 1 Day",
      detail: "Inspection Report for Plot 12B GRA, Enugu. Assigned to Ngozi.",
      kind: "listing",
      status: "under_review",
      priority: "medium",
      href: "/properties/prop-1",
    },
    {
      id: "att-4",
      title: "REQ-2026-338 - Overdue by 1 Day",
      detail: "Inspection Report for Plot 12B GRA, Enugu. Assigned to Ngozi.",
      kind: "listing",
      status: "under_review",
      priority: "medium",
      href: "/support/tck-1",
    },
    {
      id: "att-5",
      title: "Escrow documents — TX-2026-0142",
      detail: "Title pack waiting on admin review.",
      kind: "escrow",
      status: "under_review",
      priority: "medium",
      href: "/escrow/DSP-2026-0018",
    },
    {
      id: "att-6",
      title: "Agent verification — Emeka Okafor",
      detail: "CAC certificate uploaded. Awaiting approval.",
      kind: "kyc",
      status: "pending",
      priority: "high",
      href: "/users/user-emeka",
    },
  ],
};

const BASE_USERS: AdminUser[] = [
  {
    id: "user-emeka",
    fullName: "Emeka Okafor",
    email: "emeka.o@email.com",
    phone: "+234 8123 4567 891",
    role: "Agent",
    state: "Lagos",
    status: "active",
    joinedAt: "2026-05-26",
    agentStatus: "approved",
    cacNumber: "RC-1234567",
    company: "Prime Realty Partners",
    trustScore: 92,
    verified: true,
    approvedAt: "2026-05-30",
    approvedBy: "Super Admin",
    bankName: "GT Bank",
    bankAccountMasked: "5321*****34",
    totalCommissionsNgn: 12_084_100,
    documents: [
      {
        id: "doc-gov",
        name: "Government ID",
        url: "#",
        uploadedAt: "2026-03-01",
        verified: true,
      },
      {
        id: "doc-cac",
        name: "CAC Certificate",
        url: "#",
        uploadedAt: "2026-03-01",
        verified: true,
      },
      {
        id: "doc-license",
        name: "Professional License",
        url: "#",
        uploadedAt: "2026-03-01",
        verified: true,
      },
    ],
    listings: [
      {
        id: "LP-1203",
        title: "3-Bedroom Terrace — Lekki Phase 1",
        price: 12_950_000,
        status: "published",
        date: "2026-04-16",
      },
      {
        id: "LP-1204",
        title: "Mini Flat — Ikoyi",
        price: 8_400_000,
        status: "sold",
        date: "2026-03-22",
      },
      {
        id: "LP-1205",
        title: "Plot 23B — Ajah",
        price: 15_200_000,
        status: "pending",
        date: "2026-04-08",
      },
      {
        id: "LP-1206",
        title: "2-Bedroom Apartment — Yaba",
        price: 9_750_000,
        status: "published",
        date: "2026-02-14",
      },
      {
        id: "LP-1207",
        title: "Studio Apartment — VI",
        price: 6_200_000,
        status: "sold",
        date: "2026-01-30",
      },
      {
        id: "LP-1208",
        title: "4-Bedroom Duplex — Magodo",
        price: 18_500_000,
        status: "published",
        date: "2026-04-02",
      },
    ],
    commissions: [
      {
        id: "COM-1201",
        propertyTitle: "Mini Flat — Ikoyi",
        amount: 750_000,
        status: "paid",
        date: "2026-03-24",
      },
      {
        id: "COM-1202",
        propertyTitle: "3-Bedroom Terrace — Lekki Phase 1",
        amount: 1_200_000,
        status: "paid",
        date: "2026-04-18",
      },
      {
        id: "COM-1203",
        propertyTitle: "Plot 23B — Ajah",
        amount: 890_000,
        status: "pending",
        date: "2026-04-10",
      },
      {
        id: "COM-1204",
        propertyTitle: "Studio Apartment — VI",
        amount: 620_000,
        status: "paid",
        date: "2026-02-02",
      },
    ],
  },
  {
    id: "user-ada",
    fullName: "Ada Nwosu",
    email: "ada@example.com",
    phone: "08023456789",
    role: "Home_Seeker",
    state: "Abuja",
    status: "active",
    joinedAt: "2026-01-08",
  },
  {
    id: "user-chioma",
    fullName: "Chioma Eze",
    email: "chioma@example.com",
    phone: "08145551212",
    role: "Home_Seeker",
    state: "Enugu",
    status: "pending",
    joinedAt: "2026-03-22",
  },
  {
    id: "user-ibrahim",
    fullName: "Ibrahim Musa",
    email: "ibrahim@example.com",
    phone: "08056667890",
    role: "Agent",
    state: "Abuja",
    status: "flagged",
    joinedAt: "2026-02-11",
    agentStatus: "pending",
    cacNumber: "RC-220441",
  },
  {
    id: "user-funke",
    fullName: "Funke Adeyemi",
    email: "funke@example.com",
    phone: "07088990011",
    role: "Agent",
    state: "Lagos",
    status: "pending",
    joinedAt: "2026-04-02",
    agentStatus: "under_review",
    cacNumber: "RC-331002",
  },
  {
    id: "user-ngozi",
    fullName: "Ngozi Okeke",
    email: "ngozi@example.com",
    phone: "09012223344",
    role: "Home_Seeker",
    state: "Enugu",
    status: "active",
    joinedAt: "2026-04-18",
  },
  {
    id: "user-tunde",
    fullName: "Tunde Balogun",
    email: "tunde@example.com",
    phone: "08019998877",
    role: "Agent",
    state: "Lagos",
    status: "inactive",
    joinedAt: "2025-11-22",
    agentStatus: "approved",
    cacNumber: "RC-102331",
  },
  {
    id: "user-halima",
    fullName: "Halima Bello",
    email: "halima@example.com",
    phone: "08170004455",
    role: "Landlord",
    state: "Abuja",
    status: "active",
    joinedAt: "2026-03-04",
  },
  {
    id: "user-chinedu",
    fullName: "Chinedu Okonkwo",
    email: "chinedu@example.com",
    phone: "07033322111",
    role: "Home_Seeker",
    state: "Delta",
    status: "active",
    joinedAt: "2026-04-09",
  },
  {
    id: "user-yemi",
    fullName: "Yemi Alabi",
    email: "yemi@example.com",
    phone: "08024446688",
    role: "Developer",
    state: "Lagos",
    status: "pending",
    joinedAt: "2026-02-28",
  },
  {
    id: "user-amaka",
    fullName: "Amaka Ibe",
    email: "amaka@example.com",
    phone: "09087776655",
    role: "Home_Seeker",
    state: "Enugu",
    status: "flagged",
    joinedAt: "2026-01-19",
  },
  {
    id: "user-segun",
    fullName: "Segun Adeleke",
    email: "segun@example.com",
    phone: "08121110099",
    role: "Agent",
    state: "Lagos",
    status: "active",
    joinedAt: "2026-04-21",
    agentStatus: "approved",
    cacNumber: "RC-441990",
  },
];

const LISTING_SEEDS = [
  { title: "3-Bedroom Terrace — Lekki Phase 1", price: 12_950_000, status: "published" as const },
  { title: "Mini Flat — Ikoyi", price: 8_400_000, status: "sold" as const },
  { title: "Plot 23B — Ajah", price: 15_200_000, status: "pending" as const },
  { title: "2-Bedroom Apartment — Yaba", price: 9_750_000, status: "published" as const },
  { title: "Studio Apartment — VI", price: 6_200_000, status: "sold" as const },
  { title: "4-Bedroom Duplex — Magodo", price: 18_500_000, status: "published" as const },
];

const BANKS = ["GT Bank", "Access Bank", "Zenith Bank", "UBA", "First Bank"];

function withUserDetails(user: AdminUser, index: number): AdminUser {
  if (user.listings?.length) return user;

  const seller = user.role !== "Home_Seeker";
  const firstName = user.fullName.split(" ")[0] ?? "User";
  const listings = LISTING_SEEDS.slice(0, seller ? 6 : 2).map((listing, listingIndex) => ({
    id: `LP-${1200 + index * 10 + listingIndex}`,
    title: listing.title,
    price: listing.price,
    status: listing.status,
    date: `2026-0${(listingIndex % 5) + 1}-${String(10 + listingIndex).padStart(2, "0")}`,
  }));
  const commissions = seller
    ? listings.slice(0, 4).map((listing, commissionIndex) => ({
        id: `COM-${1200 + index * 10 + commissionIndex}`,
        propertyTitle: listing.title,
        amount: 400_000 + commissionIndex * 250_000,
        status: (commissionIndex === 2 ? "pending" : "paid") as "paid" | "pending",
        date: listing.date,
      }))
    : [];

  return {
    ...user,
    company:
      user.company ??
      (seller ? `${firstName} Realty Partners` : undefined),
    trustScore: user.trustScore ?? 68 + ((index * 9) % 28),
    verified: user.verified ?? user.status === "active",
    approvedAt: user.approvedAt ?? (seller ? "2026-05-30" : undefined),
    approvedBy: user.approvedBy ?? (seller ? "Super Admin" : undefined),
    bankName: user.bankName ?? (seller ? BANKS[index % BANKS.length] : undefined),
    bankAccountMasked:
      user.bankAccountMasked ?? (seller ? `532${index}*****3${index}` : undefined),
    totalCommissionsNgn:
      user.totalCommissionsNgn ??
      (seller ? commissions.reduce((sum, row) => sum + row.amount, 0) : undefined),
    cacNumber:
      user.cacNumber ?? (seller ? `RC-${100000 + index * 337}` : undefined),
    documents: user.documents ?? [
      {
        id: `${user.id}-gov`,
        name: "Government ID",
        url: "#",
        uploadedAt: "2026-03-01",
        verified: user.status === "active",
      },
      {
        id: `${user.id}-cac`,
        name: seller ? "CAC Certificate" : "Proof of Address",
        url: "#",
        uploadedAt: "2026-03-01",
        verified: user.status === "active",
      },
      {
        id: `${user.id}-license`,
        name: seller ? "Professional License" : "NIN Slip",
        url: "#",
        uploadedAt: "2026-03-01",
        verified: user.status !== "flagged",
      },
    ],
    listings,
    commissions,
  };
}

export const MOCK_USERS: AdminUser[] = BASE_USERS.map(withUserDetails);

export const MOCK_PROPERTIES: AdminProperty[] = [
  {
    id: "prop-1",
    title: "Luxury Duplex",
    type: "Duplex",
    city: "Ikoyi",
    state: "Lagos",
    price: 85_000_000,
    pricePeriod: "sale",
    boardStatus: "pending_review",
    ownerName: "Emeka Okafor",
    phone: "+234 8123 4567 891",
    description:
      "Spacious luxury duplex in Ikoyi with private compound, smart home fittings, and premium finishing throughout.",
    listedAt: "2026-05-12",
    trustScore: "pending",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: true },
      { id: "c2", label: "Site Inspection completed", done: false },
      { id: "c3", label: "Owner Identity 2026", done: false },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-05-20",
        status: "pending",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-05-20",
        status: "pending",
      },
    ],
    agent: { id: "user-emeka", name: "Emeka Okafor" },
  },
  {
    id: "prop-2",
    title: "Shortlet",
    type: "Shortlet Apartment",
    city: "Victoria Island",
    state: "Lagos",
    price: 450_000,
    pricePeriod: "month",
    boardStatus: "pending_review",
    flagged: true,
    ownerName: "Funke Adeyemi",
    phone: "07088990011",
    description:
      "Fully furnished 2-bedroom short-let apartment on Victoria Island. Premium location near Eko Hotels, with 24/7 power, gym, and rooftop pool.",
    listedAt: "2026-05-26",
    trustScore: "passed",
    images: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: true },
      { id: "c2", label: "Site Inspection completed", done: true },
      { id: "c3", label: "Owner Identity 2026", done: false },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-06-01",
        status: "pending",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-06-01",
        status: "pending",
      },
    ],
    agent: { name: "Oluwaseun Adeyemi" },
  },
  {
    id: "prop-3",
    title: "Commercial Space",
    type: "Commercial",
    city: "Wuse",
    state: "Lagos",
    price: 85_000_000,
    pricePeriod: "sale",
    boardStatus: "pending_review",
    ownerName: "Halima Bello",
    description:
      "Prime commercial floor plate suited for retail or office use, with strong frontage and dedicated parking.",
    listedAt: "2026-04-18",
    trustScore: "pending",
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: false },
      { id: "c2", label: "Site Inspection completed", done: false },
      { id: "c3", label: "Owner Identity 2026", done: true },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-04-22",
        status: "pending",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-04-22",
        status: "verified",
      },
    ],
    agent: { name: "Halima Bello" },
  },
  {
    id: "prop-4",
    title: "Office Space",
    type: "Commercial",
    city: "Victoria Island",
    state: "Lagos",
    price: 285_000_000,
    pricePeriod: "sale",
    boardStatus: "verified",
    ownerName: "Tunde Balogun",
    description:
      "Grade-A office floors on Victoria Island with generator backup, fibre connectivity, and 24-hour security.",
    listedAt: "2026-03-08",
    trustScore: "passed",
    images: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: true },
      { id: "c2", label: "Site Inspection completed", done: true },
      { id: "c3", label: "Owner Identity 2026", done: true },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-03-12",
        status: "verified",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-03-12",
        status: "verified",
      },
    ],
    agent: { id: "user-tunde", name: "Tunde Balogun" },
  },
  {
    id: "prop-5",
    title: "3-Bedroom Terrace",
    type: "Terrace",
    city: "Lekki",
    state: "Lagos",
    price: 85_000_000,
    pricePeriod: "sale",
    boardStatus: "published",
    featured: true,
    ownerName: "Emeka Okafor",
    description:
      "Modern 3-bedroom terrace in Lekki with fitted kitchen, BQ, and estate amenities.",
    listedAt: "2026-02-14",
    trustScore: "passed",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: true },
      { id: "c2", label: "Site Inspection completed", done: true },
      { id: "c3", label: "Owner Identity 2026", done: true },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-02-20",
        status: "verified",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-02-20",
        status: "verified",
      },
    ],
    agent: { id: "user-emeka", name: "Emeka Okafor" },
  },
  {
    id: "prop-6",
    title: "Mini Flat",
    type: "Apartment",
    city: "Yaba",
    state: "Lagos",
    price: 85_000_000,
    pricePeriod: "sale",
    boardStatus: "published",
    ownerName: "Segun Adeleke",
    description:
      "Compact mini flat in Yaba ideal for young professionals, close to transit and campuses.",
    listedAt: "2026-01-30",
    trustScore: "passed",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: true },
      { id: "c2", label: "Site Inspection completed", done: true },
      { id: "c3", label: "Owner Identity 2026", done: true },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-02-02",
        status: "verified",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-02-02",
        status: "verified",
      },
    ],
    agent: { id: "user-segun", name: "Segun Adeleke" },
  },
  {
    id: "prop-7",
    title: "3 Plots",
    type: "Land",
    city: "Life Camp, Asaba",
    state: "Delta",
    price: 85_000_000,
    pricePeriod: "sale",
    boardStatus: "published",
    featured: true,
    ownerName: "Halima Bello",
    description:
      "Three contiguous plots in Life Camp, Asaba — dry land with surveyed beacons and access road.",
    listedAt: "2026-04-02",
    trustScore: "passed",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1464146072230-91cabc968266?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: true },
      { id: "c2", label: "Site Inspection completed", done: true },
      { id: "c3", label: "Owner Identity 2026", done: true },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-04-05",
        status: "verified",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-04-05",
        status: "verified",
      },
    ],
    agent: { name: "Halima Bello" },
  },
  {
    id: "prop-8",
    title: "3-Bedroom Terrace",
    type: "Terrace",
    city: "Lekki",
    state: "Lagos",
    price: 85_000_000,
    pricePeriod: "sale",
    boardStatus: "published",
    featured: true,
    ownerName: "Tunde Balogun",
    description:
      "Featured Lekki terrace with open-plan living, ensuite bedrooms, and secured estate access.",
    listedAt: "2026-03-22",
    trustScore: "passed",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: true },
      { id: "c2", label: "Site Inspection completed", done: true },
      { id: "c3", label: "Owner Identity 2026", done: true },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-03-28",
        status: "verified",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-03-28",
        status: "verified",
      },
    ],
    agent: { id: "user-tunde", name: "Tunde Balogun" },
  },
  {
    id: "prop-9",
    title: "Mini Flat",
    type: "Apartment",
    city: "Yaba",
    state: "Lagos",
    price: 85_000_000,
    pricePeriod: "sale",
    boardStatus: "published",
    ownerName: "Funke Adeyemi",
    description:
      "Well-kept mini flat in Yaba with prepaid meter and reliable water supply.",
    listedAt: "2026-02-08",
    trustScore: "passed",
    images: [
      "https://images.unsplash.com/photo-1560448204-61dc36dc98c8?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: true },
      { id: "c2", label: "Site Inspection completed", done: true },
      { id: "c3", label: "Owner Identity 2026", done: true },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-02-11",
        status: "verified",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-02-11",
        status: "verified",
      },
    ],
    agent: { name: "Funke Adeyemi" },
  },
  {
    id: "prop-10",
    title: "Mini Flat",
    type: "Apartment",
    city: "Yaba",
    state: "Lagos",
    price: 85_000_000,
    pricePeriod: "sale",
    boardStatus: "published",
    ownerName: "Ibrahim Musa",
    description:
      "Bright mini flat with balcony views, tiled floors, and gated compound access.",
    listedAt: "2026-01-18",
    trustScore: "passed",
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    ],
    checklist: [
      { id: "c1", label: "Title Documents Verified", done: true },
      { id: "c2", label: "Site Inspection completed", done: true },
      { id: "c3", label: "Owner Identity 2026", done: true },
    ],
    documents: [
      {
        id: "d1",
        name: "Certificate of Occupancy",
        uploadedAt: "2026-01-22",
        status: "verified",
      },
      {
        id: "d2",
        name: "Survey Plan",
        uploadedAt: "2026-01-22",
        status: "verified",
      },
    ],
    agent: { name: "Ibrahim Musa" },
  },
];

export const MOCK_ESCROW_SUMMARY: EscrowSummary = {
  totalVolume: 511_500_000,
  inEscrow: 270_000_000,
  released: 213_000_000,
  disputed: 28_000_000,
};

const TX_0142_TIMELINE = [
  {
    id: "tx-t1",
    title: "Transaction Initiated",
    actor: "Emmanuel Nwachukwu",
    timestamp: "2026-03-01 10:30 AM",
    done: true,
  },
  {
    id: "tx-t2",
    title: "Funds Deposited",
    actor: "System",
    timestamp: "2026-03-01 10:30 AM",
    done: true,
  },
  {
    id: "tx-t3",
    title: "Funds held in Escrow",
    actor: "System",
    timestamp: "2026-03-01 10:30 AM",
    done: true,
  },
  {
    id: "tx-t4",
    title: "Dispute Filed",
    actor: "Emmanuel Nwachukwu",
    timestamp: "2026-03-01 10:30 AM",
    done: false,
  },
  {
    id: "tx-t5",
    title: "Dispute Registered",
    actor: "System",
    timestamp: "2026-03-01 10:30 AM",
    done: false,
  },
];

export const MOCK_PAYMENTS: AdminPayment[] = [
  {
    id: "TX-2026-0142",
    reference: "TX-2026-0142",
    propertyTitle: "Plot 23B - Ajah Scheme",
    amount: 28_500_000,
    currency: "NGN",
    status: "pending",
    escrowStatus: "disputed",
    paymentFor: "property",
    createdAt: "2026-04-16",
    buyerName: "Ibrahim Danladi",
    agentName: "Fatima Bello",
    provider: "VFD Escrow",
    initiatedAt: "2026-06-01",
    fundedAt: "2026-06-03",
    timeline: TX_0142_TIMELINE,
  },
  {
    id: "TX-2026-0143",
    reference: "TX-2026-0143",
    propertyTitle: "Office Space - Victoria Island",
    amount: 12_950_000,
    currency: "NGN",
    status: "success",
    escrowStatus: "released",
    paymentFor: "property",
    createdAt: "2026-04-16",
    buyerName: "Ada Nwosu",
    agentName: "Emeka Okafor",
    provider: "VFD Escrow",
    initiatedAt: "2026-04-01",
    fundedAt: "2026-04-03",
  },
  {
    id: "TX-2026-0144",
    reference: "TX-2026-0144",
    propertyTitle: "Land - 1 Plot Core Area",
    amount: 12_950_000,
    currency: "NGN",
    status: "pending",
    escrowStatus: "held_in_escrow",
    paymentFor: "property",
    createdAt: "2026-04-16",
    buyerName: "Chioma Eze",
    agentName: "Funke Adeyemi",
    provider: "VFD Escrow",
    initiatedAt: "2026-04-08",
    fundedAt: "2026-04-10",
  },
  {
    id: "TX-2026-0145",
    reference: "TX-2026-0145",
    propertyTitle: "3-Bedroom Terrace - Lekki Phase 1",
    amount: 12_950_000,
    currency: "NGN",
    status: "pending",
    escrowStatus: "initiated",
    paymentFor: "property",
    createdAt: "2026-04-16",
    buyerName: "Ibrahim Musa",
    agentName: "Emeka Okafor",
    provider: "VFD Escrow",
    initiatedAt: "2026-04-16",
  },
  {
    id: "TX-2026-0146",
    reference: "TX-2026-0146",
    propertyTitle: "Mini Flat - Ikoyi",
    amount: 12_950_000,
    currency: "NGN",
    status: "success",
    escrowStatus: "released",
    paymentFor: "property",
    createdAt: "2026-04-16",
    buyerName: "Tunde Balogun",
    agentName: "Funke Adeyemi",
    provider: "VFD Escrow",
    initiatedAt: "2026-03-22",
    fundedAt: "2026-03-24",
  },
  {
    id: "TX-2026-0147",
    reference: "TX-2026-0147",
    propertyTitle: "2 BD, Bungalow - Kubwa",
    amount: 12_950_000,
    currency: "NGN",
    status: "pending",
    escrowStatus: "held_in_escrow",
    paymentFor: "property",
    createdAt: "2026-04-16",
    buyerName: "Emmanuel Nwachukwu",
    agentName: "Fatima Bello",
    provider: "VFD Escrow",
    initiatedAt: "2026-04-12",
    fundedAt: "2026-04-14",
  },
];

export const MOCK_DISPUTES: AdminDispute[] = [
  {
    id: "DSP-2026-0018",
    status: "new",
    description:
      "Buyer claims property boundary differs from listed description with survey mismatch on the rear fence line.",
    amount: 28_000_000,
    date: "2026-06-03",
    propertyTitle: "Plot 23B - Ajah Scheme",
    buyerName: "Emmanuel Nwachukwu",
    agentName: "Fatima Bello",
    verificationId: "TX-2026-0142",
  },
  {
    id: "DSP-2026-0019",
    status: "open",
    description:
      "Buyer claims property boundary differs from listed description with missing beacons at the east corner.",
    amount: 28_000_000,
    date: "2026-06-03",
    propertyTitle: "Office Space - Victoria Island",
    buyerName: "Ada Nwosu",
    agentName: "Emeka Okafor",
  },
  {
    id: "DSP-2026-0020",
    status: "resolved",
    description:
      "Buyer claims property boundary differs from listed description with title pack now verified against survey.",
    amount: 25_000_000,
    date: "2026-06-03",
    propertyTitle: "Mini Flat - Ikoyi",
    buyerName: "Ibrahim Danladi",
    agentName: "Fatima Bello",
  },
];

export const MOCK_PAYOUTS: AdminPayout[] = [
  {
    id: "PO-2026-1201",
    agentName: "Emeka Okafor",
    amount: 750_000,
    status: "paid",
    date: "2026-03-24",
  },
  {
    id: "PO-2026-1202",
    agentName: "Funke Adeyemi",
    amount: 1_200_000,
    status: "pending",
    date: "2026-04-10",
  },
  {
    id: "PO-2026-1203",
    agentName: "Tunde Balogun",
    amount: 890_000,
    status: "paid",
    date: "2026-04-02",
  },
];

export const MOCK_VERIFICATIONS: AdminVerification[] = [
  {
    id: "ver-0142",
    paymentReference: "TX-2026-0142",
    propertyTitle: "3-bed apartment, Lekki Phase 1",
    buyerName: "Ada Nwosu",
    agentName: "Emeka Okafor",
    amount: 2_500_000,
    status: "documents_under_review",
    fundsReleased: false,
    documents: [
      { id: "d1", name: "Certificate of Occupancy", status: "under_review" },
      { id: "d2", name: "Survey Plan", status: "submitted" },
      { id: "d3", name: "Deed of Assignment", status: "pending" },
    ],
    timeline: [
      {
        id: "t1",
        title: "Funds deposited",
        description: "Paystack confirmed TX-2026-0142",
        status: "done",
        date: "2026-08-12",
      },
      {
        id: "t2",
        title: "Documents under review",
        description: "Title pack submitted by agent",
        status: "current",
        date: "2026-08-14",
      },
      {
        id: "t3",
        title: "Inspection scheduled",
        description: "Site visit not yet booked",
        status: "upcoming",
        date: "",
      },
      {
        id: "t4",
        title: "Payment disbursed",
        description: "Escrow release to agent",
        status: "upcoming",
        date: "",
      },
    ],
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-1",
    actor: "Rublist Admin",
    action: "approve",
    resource: "agent",
    summary: "Opened KYC review for Emeka Okafor",
    createdAt: "2026-08-26T10:12:00.000Z",
  },
];

export const MOCK_TICKETS: SupportTicket[] = [
  {
    id: "tck-1",
    subject: "Payout delayed on TX-2026-0142",
    requester: "Emeka Okafor",
    status: "open",
    createdAt: "2026-08-25",
  },
];

export const MOCK_NOTIFICATIONS: AdminNotification[] = [
  {
    id: "n1",
    title: "47 verifications pending",
    body: "Needs Attention inbox grew since yesterday.",
    createdAt: "2026-08-27T08:00:00.000Z",
    read: false,
  },
];
